### PR TITLE
Cemetech Support

### LINKED ISSUE #4: Cemetech support
Preliminary cemetech support is working in the appropriately named "cemetech" branch.

The currently outstanding issue is- due to some issues with hardcoding when I wrote the original downloading code years ago (issues that were sadly not cleaned up when I modularized things a year ago), as well as some apparent changes in the way files are actually downloaded off of Cemetech, downloading files doesn't work.

But everything else does! 

Making this ticket because I probably won't fix this right now, so this is a reminder to do it later.

### PR DESCRIPTION
**Pull request by TC01**
I think this is done now; finally gotten around to fixing the bugs with file infos for Cemetech.

All it's waiting on is approval from Cemetech staff that doing this sort of thing is actually okay, and then I'll merge, cleanup a few things, and then release 2.0, finally!

This will automatically fix #4.

### CODE REVIEW

**Comment by TC01** [comment]
Kerm intends to write a script to make master.index on Cemetech a thing; so we'll probably hold off releasing 2.0 until that happens.

However, I'm going to go ahead and merge anyway, then work on the other minor improvements that are on the theoretical 2.0 roadmap in master/ while we wait around for the index file to happen.

If a master index for Cemetech isn't created by the time I actually have enough free time to release 2.0 (which probably won't be for a few months), I'll look into alternatives (generating the master index file myself weekly and sticking it up on a server, probably).

**Comment by Eeems** [comment]
Need Omnimaga support as well? I could probably write something to give you support.

**Comment by TC01** [comment]
Eeems: heh, nice timing there.

Omnimaga support would be fantastic; it's last other major TI calculator repository out there that I know of (other than maybe TIPlanet? There are probably other sites too I'm unaware of or have forgotten). All that I would really need would be a way to retrieve a list of all possible files in the archives (and get a URL and some kind of human-readable name).

I could do it by spidering like how Cemetech support is currently implemented, but obviously some kind of index file or something even more sophisticated would be ideal. :)

**Comment by Eeems** [comment]
@TC01 Give me a format and I can make it so

**Pull request merged**
